export const environment = {
    production: false,
    endpoint: 'https://cloud.appwrite.io/v1',
    projectId: '6625177c31b5930630fe',
    databaseId: '663a2fa2000c900d3aea',
    collectionIdUser: 'users',
    collectionIdDocument: 'docs',
    collectionIdAppointment: 'appointments',
    collectionIdDoctors: 'doctors',
    collectionIdHolidays: 'holidays',
    collectionIdFrontEnd: 'frontEnd',
    collectionIdSerices: 'services',
    collectionIdTeam: 'team',
    collectionIdLink: 'links',
    collectionIdTitleLink: 'titleLinks',
    collectionIdFooter: 'footer',
    collectionIdNonUserApp:'nonUserAppointments',
    collectionIdContact: 'contactUs',
    bucketId: 'praxStorage'
}